#!/bin/sh

testcase "test single quotes" "-c" "echo 'ok'"
testcase "kept spaces" "-c" "echo 'a     spaces       c'  "
testcase "not a comment" "-c" "echo '#not a comment'"
testcase "; not a seperator" "-c" "echo 'a; b ;c'"
testcase "keywords in quotes" "-c" "echo 'if then ' 'elif' '    else fi'"
testcase "empty quotes" "-c" "''"
testcase "concat word + quotes" "-c" "echo a'b'c"
testcase "not closed quotes" "-c" "echo 'not ok"
testcase "backslash in quotes" "-c" "echo '\n \t \\'"
testcase "mix quotes spaces" "-c" "echo 'a' 'b' 'c'  "

testcase "quotes only" "-c" "'' '' ''"
testcase "empty" "-c" "echo ''"
testcase "quote_reserved_word1" "-c" "echo 'if'"
testcase "quote_reserved_word2" "-c" "echo 'then'"
testcase "quote_reserved_word3" "-c" "echo 'else'"
testcase "quote_reserved_word4" "-c" "'if' false; then echo ''; else echo noooooo; fi"
testcase "quote_reserved_word5" "-c" "if false; 'then' echo ''; elif true; then echo noooooo; fi"
testcase "multiple_quotes" "-c" "echo 'a''b''c'"
testcase "spaces_as_arg" "-c" "echo '   '"
testcase "simple_quote" "-c" "echo 'simple'"
testcase "bad_unterminated_quote" "-c" "'echo unterminated"
testcase "bad_quote_keywords2" "-c" "'fi'"
